[package]
name = "snake"
version = "0.1.0"
authors = ["jguidux <jeremie.guidoux@slickteam.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
piston_window = "0.108.0"
